#discord library
import discord
from discord.ext import commands

#ngrok info module
import ngrok_info

#dotenv for more secure token storing
import os
from dotenv import load_dotenv

#import json module from builtin python
import json

load_dotenv()

intents = discord.Intents.default()
intents.message_content = True

Bot = discord.Client(intents=intents)

bot = commands.Bot(command_prefix='!', intents=intents)

#open json required file (in this case the ip and port generated by get.py)
with open("get.json", "r") as read_it:
    data = json.load(read_it)
    
@bot.event
async def on_ready():
    await bot.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name='!link'))

@bot.command()
async def link(ctx):
    await ctx.send(data['ip'])

TOKEN = os.getenv("DISCORD_TOKEN")
bot.run(TOKEN)